project:
  type: website

website:
  title: "manta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles.qmd
        text: Articles
      - href: about.qmd
        text: About
  page-footer: 
    left: "Copyright &copy; Manta, Inc. 2024. All Rights Reserved"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

format:
  html:
    theme: [zephyr, style/theme.scss]
    mainfont: Tailwind
    fontsize: 1.0rem
    toc: false
