project:
  type: website

website:
  title: "manta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      light: [zephyr, style/theme-light.scss]
      dark: [zephyr, style/theme-dark.scss]
    mainfont: Tailwind
    fontsize: 1.15em
    css: styles.css
    toc: true
